### ISSUE TITLE
UI not laoding

### ISSUE THREAD

**Issue by Script20** [ottomated/turtle-gambit#11]
I have everything working and loaded but the Turtle control panel doesn't have any UI, it's just a grey screen.

**Comment by ghost** [comment]
I am also having this issue
[Image](https://imgur.com/a/kjfOUw9)

**Comment by Myoozik** [comment]
This occurs when there are no turtles connected to the server via websocket. See issue #7, I used ngrok like Ottomated did to proxy/forward the connection from the turtle to the server.

**Comment by Script20** [comment]
I did the same, I saw through the Ngrok that I had a connection.

**Comment by Myoozik** [comment]
Are you using the proper port number when launching ngrok?

**Comment by Script20** [comment]
yes 3000

**Comment by Myoozik** [comment]
Port 3000 is the one used for the frontend to communicate with the backend or something like that, the port that is used to communicate with the turtle in game is port 5757 by default when using this repo because that's what Ottomated used. Try that.

**Comment by Script20** [comment]
ngrok is using 5757? and the turtle control panel is still launching on localhost 3000

**Comment by Myoozik** [comment]
The turtle control panel will launch using port 3000 because the front-end is using that to communicate with the back-end. Launch ngrok using `ngrok http 5757` and copy and paste the new URL into the turtle.lua file on the turtle.

**Comment by Script20** [comment]
Yeah I got it working thank you so much brother!

**Comment by Myoozik** [comment]
All good, glad to hear that it works! Also since this is issue is done you should close it.

**Comment by damemer456** [comment]
what is turtle.lua?

**Comment by Myoozik** [comment]
> what is turtle.lua?

It is the file that is run on the turtle inorder for it to connect to the control panel

**Comment by watermelonpro** [comment]
Where is turtle.lua
