### ISSUE TITLE
How does one hide certain blocks?

### ISSUE THREAD

**Issue by AuroraBee** [ottomated/turtle-gambit#12]
Hiding Stone for example, would be really useful, since all vanilla ores are barely a hue diffrent from stone.

**Comment by Myoozik** [comment]
I think you can but I'm not entirely sure. I saw on one of Ottomated's twitch clips that you can hide the stone but I don't know the keybind and he might have uploaded a old version of his code to this repo that doesn't utilize that functionality.

**Comment by AuroraBee** [comment]
ill just mash every button on my keyboard ten 👍

**Comment by AuroraBee** [comment]
i was watching the stream while playing mc,
and suddenly: he says: "Let me not render Stone"
what a coincidence.
The Toggle: B (1:27:30 of his Stream)
Also: V shows the whole world.

**Comment by Myoozik** [comment]
That must be the same part of one of his steams that I also saw, thanks for the keybinds.

**Comment by AuroraBee** [comment]
np, and it does work even with andesite and such, thats perfect for me
