### ISSUE TITLE
i need help doing this

### ISSUE THREAD

**Issue by damemer456** [ottomated/turtle-gambit#21]
![Capture](https://user-images.githubusercontent.com/72422421/107906465-09cf4e80-6f06-11eb-8d4b-890fa8591440.JPG)
i get this error in frontend when using "yarn"

**Comment by Myoozik** [comment]
You need to have git installed, if you use windows download Git Bash and make sure it is added to the PATH.

**Comment by damemer456** [comment]
thanks but how to add to the PATH
im new to this

**Comment by damemer456** [comment]
nvm i did it

**Comment by damemer456** [comment]
how do i connect my turtle to the thing

**Comment by Myoozik** [comment]
See #3 and #7
