### ISSUE TITLE
how do i conncet the turtle to the web thing

### ISSUE THREAD

**Issue by damemer456** [ottomated/turtle-gambit#22]

**Comment by damemer456** [comment]
i cant get this to work im stuck on this
![Capture](https://user-images.githubusercontent.com/72422421/107975136-7da44200-6f6c-11eb-9083-41beb3ad67e9.JPG)

**Comment by watisdatikalikffffali** [comment]
@damemer456 how did you get it to start up I'm stuck on Could not find Chrome installation when I have FUCKING chrome
