### ISSUE TITLE
So... It's not working

### ISSUE THREAD

**Issue by FOREVEREALIZE** [ottomated/turtle-gambit#31]
Ok. So I just downloaded the repo, unzipped it and I ran `yarn` in the frontend folder and it told me `couldn't find the binary git`. I tested only adding NextJS and the same thing happened so I am guessing it is the NextJS binary git.

How do I fix this?

Thanks in advance, 
FOREVEREALIZE.

**Comment by watisdatikalikffffali** [comment]
@felixgames097 You need to install git bash you can get it at https://git-scm.com/downloads

**Comment by FOREVEREALIZE** [comment]
Figured it out before response and forgot about issue!
Thanks anyway!
I will close it
