### ISSUE TITLE
I don't want to use Chrome

### ISSUE THREAD

**Issue by arch-user-france1** [ottomated/turtle-gambit#49]
Chrome isn't open source! I don't want to install it on a Linux system. I rather would use chromium, brave or even the slow firefox.

How can I bypass that

**Comment by 9551-Dev** [comment]
Ok

**Comment by thrailkillr** [comment]
> Chrome isn't open source! I don't want to install it on a Linux system. I rather would use chromium, brave or even the slow firefox.
> 
> How can I bypass that

the fuck you mean slow firefox, FF is way faster than any chromium based browser
