### ISSUE TITLE
Frontend not working

### ISSUE THREAD

**Issue by FOREVEREALIZE** [ottomated/turtle-gambit#54]
> How can i make this work?
> C:\Users\User\Desktop\turtle-gambit\frontend>yarn dev
> yarn run v1.22.19
> $ next
> Browserslist: caniuse-lite is outdated. Please run:
> npx browserslist@latest --update-db
> Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser' is not defined by "exports" in C:\Users\User\Desktop\turtle-gambit\frontend\node_modules\next\node_modules\postcss\package.json
>     at new NodeError (node:internal/errors:393:5)
>     at throwExportsNotFound (node:internal/modules/esm/resolve:340:9)
>     at packageExportsResolve (node:internal/modules/esm/resolve:619:3)
>     at resolveExports (node:internal/modules/cjs/loader:492:36)
>     at Module._findPath (node:internal/modules/cjs/loader:532:31)
>     at Module._resolveFilename (node:internal/modules/cjs/loader:941:27)
>     at Module._load (node:internal/modules/cjs/loader:803:27)
>     at Module.require (node:internal/modules/cjs/loader:1021:19)
>     at require (node:internal/modules/cjs/helpers:103:18)
>     at 552 (C:\Users\User\Desktop\turtle-gambit\frontend\node_modules\next\dist\compiled\postcss-scss\scss-syntax.js:1:11590) {
>   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

_Originally posted by @Nowamax1337 in https://github.com/ottomated/turtle-gambit/issues/40#issuecomment-1242747060_

Try to run `npx browserslist@latest --update-db` on a a terminal

**Comment by Nowamax1337** [comment]
I had figured it out the problem was node.js version

**Comment by Jackaroo05** [comment]
What version of node do I need?

**Comment by sannelo** [comment]
> 

Have you solved this problem? If so, what version did you use?

**Comment by PzmuV1517** [comment]
Yeah, can you please tell us the version, all of the other issues with this topic point to here but there is no answer here!!!

**Comment by M4X40** [comment]
Any update on what version should be used, or any other fix?

**Comment by Starcalled** [comment]
FINAL EDIT: it seems that Turtle Gambit is kinda broken in modern day, since it was a one-off project that I assume was never intended to be maintained. There is a fork called [turtle-control](https://github.com/PrintedScript/turtle-control/tree/master) that (for me at least) works perfectly. 


~~Since the original post was made in September 2021, I found a node.js release from just before that time, 15.14.0, and it seems to work. Hope this helps.~~

~~EDIT: IT DOES NOT WORK. currently trying to find another version.~~
