### ISSUE TITLE
"upgrade Required"

### ISSUE THREAD

**Issue by daguy2023** [ottomated/turtle-gambit#63]
the only output is "upgrade Required" anyway to fix this, or is this just Windows?

ngrok's output:
Web Interface                 http://127.0.0.1:4040
Forwarding                    https://****.ngrok.io -> http://localhost:5757                                                                                                                                                     Connections                   ttl     opn     rt1     rt5     p50     p90                                                                             
                                       1       0       0.00    0.00    5.93    5.93                                                                                                                                                                      HTTP Requests  

GET /favicon.ico               426 Upgrade Required
GET /                          426 Upgrade Required 

I don't know how to fix this so if anyone can help, plz do

**Comment by daguy2023** [comment]
i found support elseware

**Comment by Jackaroo05** [comment]
Where did you find support?

**Comment by daguy2023** [comment]
> Where did you find support?

https://github.com/PrintedScript/turtle-control
this works, otto's doesent
