### ISSUE TITLE
World is not empty on start

### ISSUE THREAD

**Issue by AuroraBee** [ottomated/turtle-gambit#8]
how would i go about emptying all this useless junk, which is actually a part of ludwigs base?

**Comment by AuroraBee** [comment]
![grafik](https://user-images.githubusercontent.com/68081524/103413812-64d9fb80-4b7b-11eb-83ba-642ad8c8cc40.png)
currently, if you simply delete world.json you get this error whenever you move, i will take a look at the json more closely to see if theres any property that makes it non-null.

**Comment by AuroraBee** [comment]
ok its fixed.
![grafik](https://user-images.githubusercontent.com/68081524/103413939-fea1a880-4b7b-11eb-9c34-8a1ac9a5efe3.png)
[world.json.txt](https://github.com/ottomated/turtle-gambit/files/5757461/world.json.txt)
// just remove the .txt part of that file.

this seems to work, and it wont fill your map with blocks that dont exist.

**Comment by Myoozik** [comment]
Yeah Ottomated just uploaded the whole folder, including the world.json file so it'll have all of the terrain generated from the turtle before he uploaded it.

**Comment by MatthewBoi123** [comment]
so I have no idea how any of this works and am wondering if someone could help me to get this program started after downloading the turtle-gambit-master, that would be great thanks

**Comment by LostGameDev** [comment]
> ok its fixed. ![grafik](https://user-images.githubusercontent.com/68081524/103413939-fea1a880-4b7b-11eb-9c34-8a1ac9a5efe3.png) [world.json.txt](https://github.com/ottomated/turtle-gambit/files/5757461/world.json.txt) // just remove the .txt part of that file.
> 
> this seems to work, and it wont fill your map with blocks that dont exist.

but now i have blocks that you had
